; This file is for the FamiStudio Sound Engine and was generated by FamiStudio


.if FAMISTUDIO_CFG_C_BINDINGS
.export _sounds=sounds
.endif

sounds:
	.word @ntsc
	.word @ntsc
@ntsc:
	.word @sfx_ntsc_bop
	.word @sfx_ntsc_error
	.word @sfx_ntsc_score

@sfx_ntsc_bop:
	.byte $87,$5e,$88,$00,$86,$8f,$89,$f0,$01,$00
@sfx_ntsc_error:
	.byte $81,$ff,$82,$07,$80,$3f,$89,$f0,$09,$81,$89,$82,$03,$08,$00
@sfx_ntsc_score:
	.byte $81,$6b,$82,$00,$80,$3f,$89,$f0,$01,$81,$6d,$01,$81,$6e,$01,$81
	.byte $70,$01,$81,$71,$01,$81,$73,$01,$81,$74,$01,$81,$76,$01,$81,$77
	.byte $01,$81,$3f,$01,$81,$40,$02,$81,$41,$02,$81,$42,$03,$00

.export sounds
