; This file is for the FamiStudio Sound Engine and was generated by FamiStudio


.if FAMISTUDIO_CFG_C_BINDINGS
.export _sounds=sounds
.endif

sounds:
	.word @ntsc
	.word @ntsc
@ntsc:
	.word @sfx_ntsc_bop
	.word @sfx_ntsc_error
	.word @sfx_ntsc_score

@sfx_ntsc_bop:
	.byte $87,$5e,$88,$00,$86,$8f,$89,$f0,$01,$00
@sfx_ntsc_error:
	.byte $81,$ff,$82,$07,$80,$3f,$89,$f0,$09,$81,$89,$82,$03,$08,$00
@sfx_ntsc_score:
	.byte $87,$31,$88,$00,$86,$8f,$89,$f0,$09,$87,$25,$08,$00

.export sounds
